### ISSUE TITLE
Can't mount system partition as read/write

### ISSUE THREAD

**Issue by TBM13** [TeamWin/android_device_samsung_a20#1]
Trying to mount the System partition as read/write fails with error `Failed to mount '/system_root' (Invalid argument)`.
Mounting it as read-only works fine.

**Comment by TBM13** [comment]
It seems like this issue only occurs with the Android 12 GSI, so i guess i will close it

**Comment by topser9** [comment]
> It seems like this issue only occurs with the Android 12 GSI, so i guess i will close it

This problem is not caused by mount system of Twrp but it is caused by gsi rom loaded from official website and android11 ​​from phhusson but in android11 ​​from samsung this error is not found.  So it's not related to twrp.
